# Generated by Django 2.2 on 2021-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
